version: "3.9"

services:
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        env_file:
            - ./backend/.env
        expose:
            - "5000"
        healthcheck:
            test: ["CMD", "wget", "-q", "-O", "-", "http://localhost:5000/health"]
            interval: 10s
            timeout: 3s
            retries: 5

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
            args:
                VITE_API_BASE_URL: /api
        depends_on:
            backend:
                condition: service_started
        ports:
            - "8080:80"
